### ISSUE TITLE
Blue spinner won't disappear after using updateData

### ISSUE THREAD

**Issue by weilinwu97** [neuhausi/canvasXpress#138] opened 2023-08-03 06:56 UTC
Hi Issac, 

I am working on a React app to use bubble plot to show a bunch of genes and how many time has each of them been mentioned in a database. I have managed to make the plot and update the plot using the cX.updateData(newData) function. However, a blue spinner will show up after I execute the update command, and stays until I interact with the plot (more specifically, zoom in/out of the plot). Seems like someone mentions this blue spinner issue as well in #115. Wondering if you could provide some suggestion?

My data
```
const rawData = [
    {
      "gene_id": 60,
      "gene": "TP53"
      "total": 342
    },
    {
      "gene_id": 15,
      "gene": "CDKN2A",
      "total": 172
    },
    {
      "gene_id": 16,
      "gene": "CDKN2B",
      "total": 137
    },
    {
      "gene_id": 125,
      "gene": "NF1",
      "total": 131
    },
    {
      "gene_id": 21,
      "gene": "RB1",
      "total": 85
    },
    {
      "gene_id": 201,
      "gene": "PDGFRA",
      "total": 81
    },
    {
      "gene_id": 97253,
      "gene": "H3-3A",
      "total": 80
    },
    {
      "gene_id": 20788,
      "gene": "EWSR1",
      "total": 78
    },
    {
      "gene_id": 41,
      "gene": "SMARCB1",
      "total": 77
    },
    {
      "gene_id": 46,
      "gene": "ATRX",
      "total": 76
    },
    {
      "gene_id": 8427,
      "gene": "FOXO1",
      "total": 76
    },
    {
      "gene_id": 174,
      "gene": "PTEN",
      "total": 73
    },
    {
      "gene_id": 139,
      "gene": "MYCN",
      "total": 68
    },
    {
      "gene_id": 18984,
      "gene": "PAX3",
      "total": 67
    },
    {
      "gene_id": 115,
      "gene": "BRAF",
      "total": 60
    },
    {
      "gene_id": 118,
      "gene": "KRAS",
      "total": 60
    },
    {
      "gene_id": 191,
      "gene": "FGFR4",
      "total": 59
    },
    {
      "gene_id": 182,
      "gene": "ALK",
      "total": 58
    },
    {
      "gene_id": 6633,
      "gene": "FLI1",
      "total": 56
    }
``` 

My react page:
```javascript
import React, { useState, useEffect } from "react";
import { Redirect } from "react-router-dom";
import { DebounceInput } from 'react-debounce-input';

export const Genes = () => {
    const [reportableGenes, setReportableGenes] = useState(null);
    const [cX, setCX] = useState(null);
    const [topGenesToShow, setTopGenesToShow] = useState();
    const [redirect, setRedirect] = useState(null);
    const api = new API();

    const BubbleChart = (toShow) => {
        const data = {
            "x" : {
                "Gene": toShow.map((d) => d.gene_id),
            },
            "y" : {
                "data" : [
                    toShow.map((d) => d.total)
                ],
                "smps" : toShow.map((d) => d.gene),
                "vars" : ["Reportable"]
            }
        }
         
        const config = {
            "bubbleLabel":"auto",
            "circularType":"bubble",
            "graphType":"Circular",
            "colorBy":"CGC Tier",
            "hierarchy":[
               "Gene"
            ],
            "theme": "ggplot"
        }
    
        const events = {
            "click": function(o, e, t) {
                if (o.name) setRedirect(`geneEntry?gene=${o.name}`);
                
            },
        }

        if (!cX) {
            const plot = new CanvasXpress("canvasId", data, config, events);
            setCX(plot);
        } else {
            cX.updateData(data);
            cX.updateConfig(config);
            cX.updateEvents(events);
        }
    }

    useEffect(()=>{
        if (! reportableGenes) {
            const result = rawData;
            setReportableGenes(result);
            const toShow = result.data
            BubbleChart(toShow);
        }
    }, [reportableGenes])

    useEffect(async ()=>{
        if (reportableGenes && topGenesToShow) {
            const toShow = reportableGenes.data.slice(0, topGenesToShow);
            BubbleChart(toShow);
        }
    }, [topGenesToShow])

    if (redirect) {
        return <Redirect to={redirect} />;
    }

    return (
        <div className='columns'>
            <div className="column is-2 mh-0 ph-0">
                <div 
                    className="box"
                    style={{height:`${window.screen.height*0.75}px`}}
                >
                    <div className="field">
                        <div className="control">
                            <DebounceInput
                                className="input" 
                                minLength={1}
                                debounceTimeout={500}
                                placeholder="Top X genes"
                                value={topGenesToShow}
                                onChange={(event) => setTopGenesToShow(Number(event.target.value))}
                            />
                        </div>
                    </div>
                </div>
            </div>
            <div className="column is-10 mh-0 ph-0">
                <div className="box">
                    {
                        reportableGenes ? 
                            <canvas 
                                id="canvasId" 
                                width={`${window.screen.width*0.8}`} 
                                height={`${window.screen.height*0.75}`} 
                                responsive='true'
                            />
                        :
                            <progress className="progress is-small is-success" max="10">5%</progress>
                    }
                </div>
            </div>
        </div>
    );
}
```

**Comment by neuhausi** [comment] 2023-08-03 12:31
Seems to be a bug. What happens when you press ESC? BTW, is there repo I can clone to reproduce it. I am not well versed in Reacts apps :-(

**Comment by weilinwu97** [comment] 2023-08-03 23:46
Pressing ESC can get rid of the blue spinner as well. 

I am making a simplified static page for you to reproduce the behaviour. I will let you know when it is on a repo.

**Comment by neuhausi** [comment] 2023-08-04 00:00
Perfect. Thank you

**Comment by weilinwu97** [comment] 2023-08-04 01:32
Hi Issac, the repo is [here](https://github.com/weilinwu97/canvasxpress-blue-spinner-bug). The canvasxpress css and js are from `npm i canvasxpress`. 

The HTML will plot the example bubble chart, wait for two seconds, and update the data.

**Comment by neuhausi** [comment] 2023-08-04 01:48
This line is messing up the visualization:

`await new Promise(r=>setTimeout(r, 2000));`

It is not only the spinner but also the data is not being destroyed before so there are two plots on top of each other.

Question:
Do you need that line? I handle the update of data internally so you don't need to put it in a promise

Rewgards,

Isaac

**Comment by neuhausi** [comment] 2023-08-04 02:13
Look at this file. (You need to change the extension to html since github doesn't allow html files)
[brian.txt](https://github.com/neuhausi/canvasXpress/files/12256406/brian.copy.txt)

**Comment by weilinwu97** [comment] 2023-08-04 02:18
No I technically don't need that sleep line

**Comment by weilinwu97** [comment] 2023-08-04 02:25
Ah I just need to call `cX.draw()` after update, and the blue spinner is now gone.

**Comment by weilinwu97** [comment] 2023-08-04 02:28
Thank you so much

**Comment by neuhausi** [comment] 2023-08-04 02:28
Awesome. Please close the issue.

**Closed** 2023-08-04 03:13 UTC
