### ISSUE TITLE
Plot crash setting 

### ISSUE THREAD

**Issue by seoanezonjic** [neuhausi/canvasXpress#118] opened 2022-05-06 16:41 UTC
The following plot crash if the property "setMinX" is set to 0 but to 1 works perfectly:
![cX-obj_3_](https://user-images.githubusercontent.com/4126037/167175793-affb2db2-f9cb-4da8-b299-f2dd3a2a87e6.png)
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment] 2022-05-06 17:31
Can't reproduce :-(
![cX-obj_3_](https://user-images.githubusercontent.com/254923/167182908-e27b5c3d-a67b-4817-a6f4-9cc31d9e9ef0.png)

**Comment by seoanezonjic** [comment] 2022-05-09 10:35
Hi neuhasi
I give you the exact step list to reproduce the issue:
1) Take the following plot
![cX-obj_3_](https://user-images.githubusercontent.com/4126037/167392570-1326f023-f8db-4f2d-a9cc-5cfd6371a8be.png)
2) Drag and drop in:
https://canvasxpress.org/examples/boxplot-19.html
3) Go to Explore > Search Parameters  and search for setMinX.
4) Set "Current value" to 0 and click Apply
5) The plot shows loading ring and it freezes.
I hope that with this procedure you can reproduce the problem.
Thank you in advance
Pedro Seoane

**Comment by neuhausi** [comment] 2022-05-09 18:15
:-)
Fixed in version 38.5. (Please or Will close when I release the new version)
Thank you.
Isaac

**Comment by neuhausi** [comment] 2022-05-18 22:14
Please check and close ticket.
Thank you.

**Closed** 2022-05-19 07:20 UTC
